### ISSUE TITLE
Automate logging in with Google Sheets (deal with Token expiration)

### ISSUE THREAD

**Issue by peter1357908** [Longhorn-Riichi/UvUManager#21]
```
2023-07-23 19:03:54 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/peter1357908/.local/share/virtualenvs/UvUManager-DhqXTy2V/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 947, in _load_from_module_spec
    await setup(self)
  File "/home/peter1357908/UvUManager/ext/UvUManager/cog.py", line 274, in setup
    instance = UvUManager(bot)
  File "/home/peter1357908/UvUManager/ext/UvUManager/cog.py", line 34, in __init__
    self.sheet = Sheets_Interface(spreadsheet_id=SPREADSHEET_ID)
  File "/home/peter1357908/UvUManager/modules/googlesheets/sheets_interface.py", line 31, in __init__
    creds.refresh(Request())
  File "/home/peter1357908/.local/share/virtualenvs/UvUManager-DhqXTy2V/lib/python3.10/site-packages/google/oauth2/credentials.py", line 345, in refresh
    ) = reauth.refresh_grant(
  File "/home/peter1357908/.local/share/virtualenvs/UvUManager-DhqXTy2V/lib/python3.10/site-packages/google/oauth2/reauth.py", line 367, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/peter1357908/.local/share/virtualenvs/UvUManager-DhqXTy2V/lib/python3.10/site-packages/google/oauth2/_client.py", line 74, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
```

**Comment by peter1357908** [comment]
Done in #23
