### ISSUE TITLE
Deal with the on-timeout message deletion 404

### ISSUE THREAD

**Issue by peter1357908** [Longhorn-Riichi/UvUManager#30]
This likely happened because the bot tries to delete the message after the game starts. Maybe we should just remove the "delete original message on timeout" functionlity.

**Comment by peter1357908** [comment]
Okay, this also happens when we manually delete the message, through the `CANCEL` button, for example. The `CANCEL` button counts as the last interaction, and would cause the timeout to reset. 5 minutes after the `CANCEL` button press, timeout callback happens, and this error will show up in the console:
```
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-9a1292c025860d4bdef7412ba70b8b1e' coro=<TableView.on_timeout() done, defined at /home/peter/UvUManager/ext/UvUManager/table_view.py:55> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "/home/peter/UvUManager/ext/UvUManager/table_view.py", line 56, in on_timeout
    await self.original_interaction.delete_original_response()
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/discord/interactions.py", line 524, in delete_original_response
    await adapter.delete_original_interaction_response(
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

**Comment by peter1357908** [comment]
Fixed by calling `View.stop()` to allow for graceful exit.
