### ISSUE TITLE
Sometimes `START` button does nothing

### ISSUE THREAD

**Issue by peter1357908** [Longhorn-Riichi/UvUManager#31]
No error reports to Discord. Needs to check the console the next time this happens. This can be fixed by restarting bot, so there is something wrong with the bot after being left alone for a long while.

**Comment by peter1357908** [comment]
Was able to reproduce the error. Seems like the connection died somehow. Looking into this.
```python
2023-08-14 22:56:39 ERROR    discord.ui.view Ignoring exception in view <TableView timeout=300 children=8> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='START WITH AI' emoji=None row=1>
Traceback (most recent call last):
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/home/peter/UvUManager/ext/UvUManager/table_view.py", line 312, in start_with_ai_button
    await self.start_game(account_ids=[
  File "/home/peter/UvUManager/modules/mahjongsoul/contest_manager.py", line 189, in start_game
    await self.call('lockGamePlayer', account_id=account_id)
  File "/home/peter/UvUManager/modules/mahjongsoul/contest_manager.py", line 79, in call
    return await super().call(methodName, **msgFields)
  File "/home/peter/UvUManager/modules/pymjsoul/channel.py", line 271, in call
    resData = await self.send(msgName, reqMessage.SerializeToString())
  File "/home/peter/UvUManager/modules/pymjsoul/channel.py", line 222, in send
    await self.websocket.send(message)
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/home/peter/.local/share/virtualenvs/UvUManager-2s-jCTM7/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```

**Comment by peter1357908** [comment]
Just a Websocket error. What caused it remains to be investigated (it's likely related to connection drop during maintenance, etc.), but the error itself will be caught and acted on now.
